version: '3'

services:
  db:
    image: postgres:13.1
    container_name: joplindb
    volumes:
      - /home/redscape/joplin-server/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - APP_PORT=${APP_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks: 
      - traefik
      - traefik_lan
  app:
    image: joplin/server:latest
    container_name: joplinapp
    depends_on:
      - db
    ports:
     - "22300:22300"
    restart: unless-stopped
    environment:
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=${DB_CLIENT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:      
      - traefik
      - traefik_lan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joplin-http.entrypoints=http"
      - "traefik.http.routers.joplin-http.rule=Host(`joplin.glarose.fr`)"
      - "traefik.http.routers.joplin-http.middlewares=joplin-https@docker"
      - "traefik.http.routers.joplin.entrypoints=https"
      - "traefik.http.routers.joplin.rule=Host(`joplin.glarose.fr`)"
      - "traefik.http.routers.joplin.tls=true"
      - "traefik.http.routers.joplin.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik_lan"
      - "traefik.http.middlewares.joplin.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.joplin.headers.accessControlAllowOrigin=*"
      - "traefik.http.routers.joplin.service=joplin@file"
      - "traefik.http.services.joplin.loadbalancer.servers.port=22300"
networks:
  traefik_lan:
    external: true
  traefik:
    external: true

