version: '3'

services:
  redscapemusicdb:
    image: mariadb:${MARIADBVERSION}
    container_name: redscapemusicdb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MYSQL_DATABASE=${MYSQLDB}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - traefik_lan  

  redscapemusic_wp:
    image: wordpress:${WPVERSION}
    container_name: redscapemusic_wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=redscapemusicdb
      - WORDPRESS_DB_USER=${MYSQLUSER}
      - WORDPRESS_DB_PASSWORD=${MYSQLPASSWORD}
      - WORDPRESS_DB_NAME=${MYSQLDB}
    volumes:
      - /home/redscape/docker_wordpress/redscapemusic/data:/var/www/html
      - /home/redscape/docker_wordpress/redscapemusic/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on: 
      - redscapemusicdb
    networks:
      - traefik_lan

  redscapemusic_nginx:  
    image: nginx:${NGINXVERSION}
    container_name: redscapemusic_nginx
    restart: unless-stopped
    ports:
      - "89:80"
      - "449:443"
    volumes:
      - /home/redscape/docker_wordpress/redscapemusic/data:/var/www/html
      - nginxlogs:/var/log/nginx
      - ./nginx:/etc/nginx
    links:
      - redscapemusic_wp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redscapemusic-http.entrypoints=http"
      - "traefik.http.routers.redscapemusic-http.rule=Host(`redscapemusic.com`)"
      - "traefik.http.routers.redscapemusic-http.middlewares=redscapemusic-https@docker"
      - "traefik.http.routers.redscapemusic.entrypoints=https"
      - "traefik.http.routers.redscapemusic.rule=Host(`redscapemusic.com`)"
      - "traefik.http.routers.redscapemusic.middlewares=nextcloud-caldav@docker"
      - "traefik.http.routers.redscapemusic.tls=true"
      - "traefik.http.routers.redscapemusic.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik_lan"
      - "traefik.http.middlewares.redscapemusic.headers.customrequestheaders.X-Forwarded-Proto=websecure"
      - "traefik.http.middlewares.redscapemusic.headers.accessControlAllowOrigin=*"
      - "traefik.http.routers.redscapemusic.service=redscapemusic@file"
      - "traefik.http.services.redscapemusic.loadbalancer.servers.port=89"
    networks:
      - traefik_lan
volumes:
  dbdata:
  nginxlogs:
  dataredis:

networks:
  traefik_lan:
    external: true