version: '3'

services:
  allianceagencydb:
    image: mariadb:${MARIADBVERSION}
    container_name: allianceagencydb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MYSQL_DATABASE=${MYSQLDB}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - traefik_lan  

  allianceagency_wp:
    image: wordpress:${WPVERSION}
    container_name: allianceagency_wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=allianceagencydb
      - WORDPRESS_DB_USER=${MYSQLUSER}
      - WORDPRESS_DB_PASSWORD=${MYSQLPASSWORD}
      - WORDPRESS_DB_NAME=${MYSQLDB}
    volumes:
      - /home/redscape/docker_wordpress/allianceagency/data:/var/www/html
      - /home/redscape/docker_wordpress/allianceagency/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on: 
      - allianceagencydb
    networks:
      - traefik_lan

  allianceagency_nginx:  
    image: nginx:${NGINXVERSION}
    container_name: allianceagency_nginx
    restart: unless-stopped
    ports:
      - "82:80"
      - "445:443"
    volumes:
      - /home/redscape/docker_wordpress/allianceagency/data:/var/www/html
      - nginxlogs:/var/log/nginx
      - ./nginx:/etc/nginx
    links:
      - allianceagency_wp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.allianceagency-http.entrypoints=http"
      - "traefik.http.routers.allianceagency-http.rule=Host(`allianceagency.fr`)"
      - "traefik.http.routers.allianceagency-http.middlewares=allianceagency-https@docker"
      - "traefik.http.routers.allianceagency.entrypoints=https"
      - "traefik.http.routers.allianceagency.rule=Host(`allianceagency.fr`)"
      - "traefik.http.routers.allianceagency.tls=true"
      - "traefik.http.routers.allianceagency.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik_lan"
      - "traefik.http.middlewares.allianceagency.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.allianceagency.headers.accessControlAllowOrigin=*"
      - "traefik.http.routers.allianceagency.service=allianceagency@file"
      - "traefik.http.services.allianceagency.loadbalancer.servers.port=82"
    networks:
      - traefik_lan
  
volumes:
  dbdata:
  nginxlogs:

networks:
  traefik_lan:
    external: true