http:
  #routers
  routers:
    nextcloud:
      rule: "Host(`nextcloud.glarose.fr`)"
      entryPoints:
        - https
      middlewares:
        - https-redirect
        - default-headers
      tls: {}
      service: nextcloud
    redscapemusic:
      rule: "Host(`redscapemusic.com`)"
      entryPoints:
        - https
      middlewares:
        - https-redirect
        - default-headers
      tls: {}
      service: redscapemusic
    aspacemr:
      rule: "Host(`aspacemr.fr`)"
      entryPoints:
        - https
      middlewares:
        - https-redirect
        - default-headers
      tls: {}
      service: aspacemr
    freshflavour:
      rule: "Host(`freshflavour.fr`)"
      entryPoints:
        - https
      middlewares:
        - https-redirect
        - default-headers
      tls: {}
      service: freshflavour
    allianceagency:
      rule: "Host(`alliance-agency.fr`)"
      entryPoints:
        - https
      middlewares:
        - https-redirect
        - default-headers
      tls: {}
      service: allianceagency
    joplin:
      rule: "Host(`joplin.glarose.fr`)"
      entryPoints:
        - https
      middlewares:
        - https-redirect
        - default-headers
      tls: {}
      service: joplin
    lesabyssales:
      rule: "Host(`lesabyssales.redscapemusic.com`)"
      entryPoints:
        - https
      middlewares:
        - https-redirect
        - default-headers
      tls: {}
      service: lesabyssales
  #services
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://192.168.9.40:80"
        passHostHeader: true
    redscapemusic:
      loadBalancer:
        servers:
          - url: "http://192.168.9.20:89"
        passHostHeader: true
    aspacemr:
      loadBalancer:
        servers:
          - url: "http://192.168.9.20:81"
        passHostHeader: true
    freshflavour:
      loadBalancer:
        servers:
          - url: "http://192.168.9.20:82"
        passHostHeader: true
    allianceagency:
      loadBalancer:
        servers:
          - url: "http://192.168.9.20:83"
        passHostHeader: true
    joplin:
      loadBalancer:
        servers:
          - url: "http://192.168.9.40:22300"
        passHostHeader: true
    lesabyssales:
      loadBalancer:
        servers:
          - url: "http://192.168.9.20:84"
        passHostHeader: true
  #middlewares
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"
        - "173.245.48.0/20"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "172.64.0.0/13"
        - "131.0.72.0/22"
        - "172.65.46.0/24"
    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers

    
