version: '3'

services:
  freshflavourdb:
    image: mariadb:${MARIADBVERSION}
    container_name: freshflavourdb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MYSQL_DATABASE=${MYSQLDB}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - traefik_lan  

  freshflavour_wp:
    image: wordpress:${WPVERSION}
    container_name: freshflavour_wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=freshflavourdb
      - WORDPRESS_DB_USER=${MYSQLUSER}
      - WORDPRESS_DB_PASSWORD=${MYSQLPASSWORD}
      - WORDPRESS_DB_NAME=${MYSQLDB}
    volumes:
      - /home/redscape/docker_wordpress/freshflavour/data:/var/www/html
      - /home/redscape/docker_wordpress/freshflavour/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on: 
      - freshflavourdb
    networks:
      - traefik_lan

  freshflavour_nginx:  
    image: nginx:${NGINXVERSION}
    container_name: freshflavour_nginx
    restart: unless-stopped
    ports:
      - "82:80"
      - "445:443"
    volumes:
      - /home/redscape/docker_wordpress/freshflavour/data:/var/www/html
      - nginxlogs:/var/log/nginx
      - ./nginx:/etc/nginx
    links:
      - freshflavour_wp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshflavour-http.entrypoints=http"
      - "traefik.http.routers.freshflavour-http.rule=Host(`freshflavour.fr`)"
      - "traefik.http.routers.freshflavour-http.middlewares=freshflavour-https@docker"
      - "traefik.http.routers.freshflavour.entrypoints=https"
      - "traefik.http.routers.freshflavour.rule=Host(`freshflavour.fr`)"
      - "traefik.http.routers.freshflavour.tls=true"
      - "traefik.http.routers.freshflavour.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik_lan"
      - "traefik.http.middlewares.freshflavour.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.freshflavour.headers.accessControlAllowOrigin=*"
      - "traefik.http.routers.freshflavour.service=freshflavour@file"
      - "traefik.http.services.freshflavour.loadbalancer.servers.port=82"
    networks:
      - traefik_lan
  
volumes:
  dbdata:
  nginxlogs:

networks:
  traefik_lan:
    external: true