version: "3.3"

services:
  mc:
    image: itzg/minecraft-server:2021.17.0-java16-openj9
    ports:
      - 25565:25565
    volumes:
      - /home/redscape/minecraft/data:/data
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Minecraft Ghislain & Yannis"
      MOTD: "A beautiful place to build our world"
      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: 1.5G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minecraft.entrypoints=http"
      - "traefik.http.routers.minecraft-http.rule=Host(`minecraft.glarose.fr`)"
      - "traefik.http.routers.minecraft-http.middlewares=minecraft-https@docker"
      - "traefik.http.routers.minecraft.entrypoints=https"
      - "traefik.http.routers.minecraft.rule=Host(`minecraft.glarose.fr`)"
      - "traefik.http.routers.minecraft.tls=true"
      - "traefik.http.routers.minecraft.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik_lan"
      - "traefik.http.routers.minecraft.service=minecraft@file"
      - "traefik.http.services.minecraft.loadbalancer.servers.port=25565"
    networks:
      - traefik_lan
networks:      
  traefik_lan:
    external: true