version: '3'

services:
  lesabyssalesdb:
    image: mariadb:${MARIADBVERSION}
    container_name: lesabyssalesdb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MYSQL_DATABASE=${MYSQLDB}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - traefik_lan  

  lesabyssales_wp:
    image: wordpress:${WPVERSION}
    container_name: lesabyssales_wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=lesabyssalesdb
      - WORDPRESS_DB_USER=${MYSQLUSER}
      - WORDPRESS_DB_PASSWORD=${MYSQLPASSWORD}
      - WORDPRESS_DB_NAME=${MYSQLDB}
    volumes:
      - /home/redscape/docker_wordpress/lesabyssales/data:/var/www/html
      - /home/redscape/docker_wordpress/lesabyssales/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on: 
      - lesabyssalesdb
    networks:
      - traefik_lan

  lesabyssales_nginx:  
    image: nginx:${NGINXVERSION}
    container_name: lesabyssales_nginx
    restart: unless-stopped
    ports:
      - "84:80"
      - "446:443"
    volumes:
      - /home/redscape/docker_wordpress/lesabyssales/data:/var/www/html
      - nginxlogs:/var/log/nginx
      - ./nginx:/etc/nginx
    links:
      - lesabyssales_wp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lesabyssales-http.entrypoints=http"
      - "traefik.http.routers.lesabyssales-http.rule=Host(`lesabyssales.redscapemusic.com`)"
      - "traefik.http.routers.lesabyssales-http.middlewares=lesabyssales-https@docker"
      - "traefik.http.routers.lesabyssales.entrypoints=https"
      - "traefik.http.routers.lesabyssales.rule=Host(`lesabyssales.redscapemusic.com`)"
      - "traefik.http.routers.lesabyssales.middlewares=nextcloud-caldav@docker"
      - "traefik.http.routers.lesabyssales.tls=true"
      - "traefik.http.routers.lesabyssales.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik_lan"
      - "traefik.http.middlewares.lesabyssales.headers.customrequestheaders.X-Forwarded-Proto=websecure"
      - "traefik.http.middlewares.lesabyssales.headers.accessControlAllowOrigin=*"
      - "traefik.http.routers.lesabyssales.service=lesabyssales@file"
      - "traefik.http.services.lesabyssales.loadbalancer.servers.port=84"
    networks:
      - traefik_lan
volumes:
  dbdata:
  nginxlogs:
  dataredis:

networks:
  traefik_lan:
    external: true